avrgirl-arduino.js
Auto-sniffing ports was broken on Windows.
Windows lists its productId within the pnpId, or 'plug n play id' property. If the productId property is blank, grab it from the pnpId Prop instead.
=> fix auto-sniff pid detection bug on windows

avrgirl-arduino.js
`pnpId` doesn't always contain `PID_` on Windows, so the `exec` blows up.
=> Catch PID regex errors on Windows

README.md
Fixes #49 
If `avrgirl-arduino` is the first thing you're doing with your new Arduino on Windows, you can run into some trouble!  Windows can require extra steps before the Arduino is usable, including the installation of an Arduino IDE and Windows drivers.  
Here's a small note for those users linking them to a guide for Windows setup and instructing them they only need to complete steps 1-4.
=> Add Arduino IDE and Driver installation for Windows users to README

avrgirl-arduino.js, lib/avr109.js, lib/connection.js, lib/protocol.js, lib/stk500v1.js, lib/stk500v2.js, lib/tools.js, package.json, tests/avrgirl-arduino.spec.js, tests/connection.spec.js, tests/helpers/mockSerial.js, tests/helpers/mockStk500.js, tests/protocol.spec.js
Running `npm test` made all these changes.
=> Add jshint to devdeps and lint

package.json
3.1.2 will probably be the last of the serial port 3.x releases. 3.x didn't change the api beyond not removing event handlers which don’t seem to be used here. It primarily fixes bugs.
https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/changelog.md#version-205 
Notable changes
- Node 6 support
- Memory leaks removed
- possible error handling (`port.on(‘error’)` often didn’t work in the past as all event handlers were removed on disconnect or close)
- Much better error messages
- Bug fixes around opening and closing ports on OSX
I checked the usage in the following packages and they appear to not cause any issues with the changes.
- stk500
- chip.avr.avr109
Helps #57
Closes #68
=> Upgrade SerialPort from 2.0.5 to 3.1.2

boards.js, package.json
Hi!
im doing a little research with an Arduino Mega modification called [ME Auriga](http://www.makeblock.com/electronic-robot-kit-series-STEM/me-auriga). Looks fine and can upload simple codes, so i add the productId. 
Also update the stk500-v2 library to 1.0.2 (its a minor change to fix a bug when is used inside a chrome extension with browserify).
Thanks! 🎄
=> Add ME Auriga as mega board, update stk500-v2 

lib/protocol.js, tests/protocol.spec.js
This allows the library users custom debug function to be used within the protocol layers. `avrgirl-arduino.js` currently guarantees a function is passed in as `options.debug`.
An alternative, is to have similar code to `avrgirl-arduino.js` in `lib/protocol.js`:
```js
if (options.debug === true) {
this.debug = console.log.bind(console);
} else if (typeof options.debug === 'function') {
this.debug = options.debug;
} else {
this.debug = function() {};
}
```
Let know know which option is preferred.
=> Use options.debug in protocol as debug function

boards.js
A simple change to get my Genuino Micro board flashing.
0x8037 is present in the list already but the bootloader PID is 0x0237, which is needed to detect the boards after a CDC reset.
This also corresponds to the following entry in the AVR core: https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/boards.txt#L353
=> Add Genuino Micro product id

package.json
Changed to https so those behind firewalls can install avrgirl without SSH access.
I work at a company that prohibits SSH access out of the network.  Since two of the dependencies had git: URLs instead of HTTPS, I was unable to install this at work.  I changed the package.json to use all https: URLs instead and it worked perfectly.
Thanks,
- James
=> Updated package.json to change from git: to https:

lib/avr109.js
There are some devices out there that can't be reset from software, and need a physical button pressed to put them into bootloader mode. On these devices, trying to reset them is not going to work, so it is best skipped.
As such, this little change adds a `manualReset` flag to the board options, which when set, allows `Avr109._reset` to return immediately, skipping the whole reset dance. As a consequence, boards with the flag set, will have to be reset by the user before calling the `_upload` (or `avrgirl.flash`) method.
Tested & works on the Shortcut keyboard, and fixes #111.
Please let me know if you don't like the name of the flag - or anything else with the pull request - and I'll update it accordingly!
=> Support devices that can't be reset from software

avrgirl-arduino.js, boards.js
This PR is a resolution for #122.
It exposes a new static method named `listKnownBoards` using the keys from the `byName` object which is keyed by the board name. I went with this over `listBoards` as I figured that might be useful in future as an instance method which also includes things such as custom boards.
I also added aliasing to remove the duplication mentioned in the stream today, and verified that both names come back appropriately in the resulting call to `listKnownBoards`. It might be that we don't want the aliases to come back in this list though, if so just let me know and I can tweak it to omit them.
Here's an example output:
```javascript
> avr.listKnownBoards()
[ 'uno',
'micro',
'imuduino',
'leonardo',
'arduboy',
'feather',
'little-bits',
'blend-micro',
'nano', …
```
=> Provide a static helper to list known boards

boards.js
It works on my Windows 10 computer.
=> Added support for Circuit Playground Classic in boards.js

README.md, tests/demos/circuit-playground-classic.js
I tested the recent release of `avrgirl-arduino` with support for the [Adafruit Circuit Playground Classic](https://www.adafruit.com/product/3000) against the board. 
**Result:**
```
hipsterbrown:avrgirl-arduino (master) $ node tests/demos/circuit-playground-classic.js
found circuit-playground-classic on port /dev/cu.usbmodem1421
resetting board...
reset complete.
connected
flashing, please wait...
flash complete.
done.
hipsterbrown:avrgirl-arduino (master) $
```
**Success!!!** :tada:
This PR adds a test demo file for the `circuit-playground-classic` and updates the README to include the board in the supported boards list (I also added myself to the list of contributors if this is approved).
=> Adafruit Circuit Playground Test

.travis.yml, gulpfile.js, package-lock.json, package.json
Updates node SerialPort dependency to the latest version to also work with node 10.
Fixes issues #156 and #145 
- [ x ] Bug fix (non-breaking change which fixes an issue)
No code changes at this point, only a package update.
- Operating system and version
MacOS 10.12
- NodeJS version
6, 8, 10
- Arduino Board being used
Nano & Uno
=> Update dependency on node Serialport to v6

README.md, boards.js
This change adds a new boards entry for Arduino Nano boards that ship with the new bootloader (baud 115200).
The corresponding change in the Arduino AVR core can be found here: https://github.com/arduino/ArduinoCore-avr/commit/1b14cc07331268e95eddcce2cc67e29ed667e62f
Note: instead of changing the current nano entry, I've opted to add a new one for backwards compatibility.
cc/ @facchinm
Please delete options that are not relevant.
- Operating system and version: macOS 10.14.2
- Avrgirl Arduino version: master / c502da52354514cba5fef9ef6bfad297d82e7d8d
- NodeJS version: v10.15.0 
- Arduino Board being used: Arduino Nano with new boot loader (115200 baud)
=>  Add boards entry for Nano with new bootloader

lib/stk500v1.js
While tracking down some "Sending 3020: receiveData timeout after 400ms" STK500v1 errors on Chrome OS 74, I noticed the stk500v1 reset code in this project does not match the procedure in`avrdude`: https://github.com/kcuzner/avrdude/blob/master/avrdude/arduino.c#L95-L104
The port open is fast enough to trigger a reset and perform uploads. However if you add a `setTimeout` of 5 seconds after `_this.serialPort.open(function(error) {` in [stk500v1.js](https://github.com/noopkat/avrgirl-arduino/blob/master/lib/stk500v1.js) the board doesn't actually reset (it's still running the previously loaded sketch).
For Chrome OS 74, the following `stk500` pull request was also needed for sequential uploads to work without unplugging the USB cable: https://github.com/jacobrosenthal/js-stk500v1/pull/9 …
=> stk500v1: reset like avrdude - DTR low 250 ms, then DTR high 50 ms

avrgirl-arduino.js, tests/avrgirl-arduino.spec.js
Fixes #114
This change allows to define a sparse board object:  `new Avrgirl({ board: { name: 'uno' } })`.
To be valid, the `board` argument must be an object with only the `name` property defined (ie.  `new Avrgirl({ board: { name: 'uno', protocol: 'stk500v1' } })` will not be considered as sparse, and wiil fail latter because of missing properties).
Also adds associated tests.
=> Adding support for sparse custom board

README.md, bin/cli.js
Fixes #97
This PR allows to provide a custom board specification in the CLI, eg:
```
avrgirl-arduino flash -f Blink.cpp.hex -a custom.json
```
This change being in the CLI part, I am not sure what is the appropriate way to test it.
There is currently not a lot of documentation for custom boards (looking at you #151), so I did not add documentation on the expected JSON format. The only tricky part, I think, is the `signature` field where we create the `Buffer` from the input JSON array. Maybe adding a CLI option to display the JSON specification for a supported board may help ?
Maybe we want to the feature to the library part? It may make sense to handle the `Buffer` creation for the user.
I tried to provide an accurate error message, but using the same argument, it is kind of hard to …
=> Adding support for custom boards in the cli

boards.js
Add Sparkfun [Redboard](https://www.sparkfun.com/products/13975) to the boards.js `uno` section.  The board is compatible with Arduino Uno.
-  ATmega328 microcontroller with Optiboot (UNO) Bootloader
-  USB Programming Facilitated by the Ubiquitous FTDI FT231X
-  Input voltage - 7-15V
-  0-5V outputs with 3.3V compatible inputs
-  14 Digital I/O Pins (6 PWM outputs)
-  6 Analog Inputs
-  ISP Header
-  32k Flash Memory
-  16MHz Clock Speed
-  All SMD Construction
-  R3 Shield Compatible
-  Red PCB!
=> [uno] add sparkfun redboard productId

tests/demos/webserial/index.html
I couldn't get the js to load properly without having a charset attr on the <script>. Probably has something to do with my particular OS.
=> webserial demo: script is utf-8

tests/demos/webserial/README.md
Hi, just updating the web serial readme to include the flag that needs to be enabled to run the example on the stable branch of Chrome. Thanks!
=> Update web serial demo readme with chrome flag

.github/workflows/gh-release.yml
We don't want the changelog github action to trigger on any push to master, just tags.
=> remove master branch trigger for changelog gh action
